### ISSUE TITLE
how to remove the color of the fish symble

### ISSUE THREAD

**Issue by fyeeme** [oh-my-fish/theme-default#11]
https://user-images.githubusercontent.com/6078758/32414540-62e5ab88-c264-11e7-8a0f-8e1f4599906a.png

macos 10.13.1  termial and iterm both have this problem

**Comment by sagebind** [comment]
See https://github.com/oh-my-fish/oh-my-fish/issues/440 and https://github.com/oh-my-fish/oh-my-fish/issues/573 for additional reports of this issue.

**Comment by larslevie** [comment]
👍

**Comment by tonatiuh** [comment]
What about 

```
$ omf cd default
$ vim fish_prompt.fish
```

and apply this change

```
-  set -l success_color    (set_color $fish_pager_color_progress ^/dev/null; or set_color cyan)
+  set -l success_color    (set_color cyan)
```

?

Just sharing in case it helps anyone. That worked for me.

**Comment by fyeeme** [comment]
@tonatiuh works for me too
