### ISSUE TITLE
prompt show messy code in windows WSL

### ISSUE THREAD

**Issue by subcrew** [oh-my-fish/theme-default#16]
when i install theme-default in windows WSL with omf, some characters show messy code:
<img width="194" alt="capture" src="https://user-images.githubusercontent.com/8164151/52842768-15cb7e80-313b-11e9-9d63-8854569c36f0.PNG">

**Comment by scorphus** [comment]
It looks like you're missing powerline fonts. I found the following guide on Google:

https://iamnotmyself.com/2017/04/15/setting-up-powerline-shell-on-windows-subsystem-for-linux/

I hope it helps. In case it doesn't, please feel free to reopen this issue.

**Comment by subcrew** [comment]
> It looks like you're missing powerline fonts. I found the following guide on Google:
> 
> https://iamnotmyself.com/2017/04/15/setting-up-powerline-shell-on-windows-subsystem-for-linux/
> 
> I hope it helps. In case it doesn't, please feel free to reopen this issue.

It helps, thanks scorphus
