### ISSUE TITLE
Add `git stash` indicator

### ISSUE THREAD

**Issue by alex-grover** [oh-my-fish/theme-default#19]
This is a nice feature that the [`pure`](https://github.com/pure-fish/pure) prompt has. It would be easy to adapt their implementation ([here](https://github.com/pure-fish/pure/blob/440dcb3adcb5ab5f134a7f7079a5cea7c1c1c44c/functions/_pure_prompt_git_stash.fish)) into this prompt.

How it looks in `pure`, excuse the color scheme. Just installed it for this example screenshot
<img width="419" alt="Screen Shot 2021-03-11 at 13 48 56" src="https://user-images.githubusercontent.com/3088615/110859612-8a1c7180-8270-11eb-83cf-8801b29af937.png">

Not sure what the contribution process is for this repo, but happy to open a PR if this would be accepted!

**Comment by alex-grover** [comment]
@scorphus sorry to ping directly, looks like you're the only active member lately. please let me know if this change would be accepted, or else i can close the issue

**Comment by scorphus** [comment]
Hi, @ajgrover. No need to sorry, actually thanks for the ping.

I think this could be a nice feature to have. It would be nice if it was a completely opt-in feature, with accompanying documentation on how to activate. What do you think?

**Comment by alex-grover** [comment]
sounds good to me - will submit a PR when i have some time!

**Comment by alex-grover** [comment]
hi @scorphus, would appreciate a look at the PR if you have some time!

**Comment by alex-grover** [comment]
@scorphus one more ping - would love to get this merged

**Comment by scorphus** [comment]
Hey, sorry for not replying for so long.

I reckon that if changes are stashed and new changes are made, then the dirty indicator will have precedence, right? Can you please post screenshots of how each of these cases would look like?

Thanks!

**Comment by alex-grover** [comment]
added in the PR!
