### ISSUE TITLE
Use default theme with fisherman makes prompt shows strange

### ISSUE THREAD

**Issue by goofansu** [oh-my-fish/theme-default#8]
<img width="240" alt="screenshot of iterm2 17-1-22 1-57-19" src="https://cloud.githubusercontent.com/assets/1143191/22176466/1de4a3dc-e046-11e6-84f9-915992b886f9.png">

I installed this theme with fisherman using `fisher omf/theme-default`.

Everything works great except the normal prompt has a blue background as in the screenshot.

Does anyone encounter the same problem?

**Comment by shelldandy** [comment]
I'm having the same issue 😢

**Comment by shelldandy** [comment]
Hey @goofansu I found out what it was apparently after Fish got updated to 2.4 some colors where intentionally changed so if you want to set it up as expected do:

On your `init.fish` or `conf.fish` file
`set fish_pager_color_progress cyan`

Reference: https://github.com/fish-shell/fish-shell/issues/3555

**Comment by goofansu** [comment]
@mike3run thank you. I'm using [simple](https://github.com/fisherman/simple) theme now and found it more comfortable to use.
